### ISSUE TITLE
Examples do not compile

### ISSUE THREAD

**Issue by jrubencr** [STONElibrary/arduino_lib#2]
I have downloaded the library using the manager in Arduino.
My board is an Arduino UNO (ATMEGA328P).
 
None of the examples even compile, here is the error output for the stone_receive.cpp:

`stone_receive.cpp:21:1: error: 'frame_link' does not name a type; did you mean 'write_line'?
 frame_link * initLink(){
 ^~~~~~~~~~
 write_line
stone_receive.cpp:30:1: error: 'frame_link' does not name a type; did you mean 'write_line'?
 frame_link * frame_link_p=initLink();
 ^~~~~~~~~~
 write_line
stone_receive.cpp:32:1: error: 'frame_link' does not name a type; did you mean 'write_line'?
 frame_link * additional(frame_link * p, int base_offset) {
 ^~~~~~~~~~
 write_line
stone_receive.cpp:45:1: error: 'frame_link' does not name a type; did you mean 'write_line'?
 frame_link * delElem(frame_link * p) {
 ^~~~~~~~~~
 write_line
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive_group.cpp: In function 'void receive_parse()':
stone_receive_group.cpp:371:7: error: 'case_file_rw' was not declared in this scope
       case_file_rw();
       ^~~~~~~~~~~~
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp: In function 'void serial_receive()':
stone_receive.cpp:102:24: error: too many arguments to function 'void receive_parse()'
         receive_parse(0);
                        ^
In file included from C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp:12:0:
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone.h:165:6: note: declared here
 void receive_parse (void);
      ^~~~~~~~~~~~~
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp: In function 'int find_frame_(unsigned char*)':
stone_receive.cpp:134:15: error: 'frame_link_p' was not declared in this scope
               frame_link_p = additional(frame_link_p, num-6);
               ^~~~~~~~~~~~
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp:134:15: note: suggested alternative: 'write_line'
               frame_link_p = additional(frame_link_p, num-6);
               ^~~~~~~~~~~~
               write_line
stone_receive.cpp:134:30: error: 'additional' was not declared in this scope
               frame_link_p = additional(frame_link_p, num-6);
                              ^~~~~~~~~~
stone_receive.cpp:142:7: error: 'frame_link_p' was not declared in this scope
   if (frame_link_p->frame_count>0)
       ^~~~~~~~~~~~
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp:142:7: note: suggested alternative: 'write_line'
   if (frame_link_p->frame_count>0)
       ^~~~~~~~~~~~
       write_line
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp: In function 'void serial_receive_frame(short unsigned int)':
stone_receive.cpp:162:3: error: 'frame_link' was not declared in this scope
   frame_link * t = frame_link_p;
   ^~~~~~~~~~
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp:162:3: note: suggested alternative: 'write_line'
   frame_link * t = frame_link_p;
   ^~~~~~~~~~
   write_line
stone_receive.cpp:162:16: error: 't' was not declared in this scope
   frame_link * t = frame_link_p;
                ^
stone_receive.cpp:162:20: error: 'frame_link_p' was not declared in this scope
   frame_link * t = frame_link_p;
                    ^~~~~~~~~~~~
C:\Users\joser\AppData\Local\Temp\arduino_build_308636\sketch\stone_receive.cpp:162:20: note: suggested alternative: 'write_line'
   frame_link * t = frame_link_p;
                    ^~~~~~~~~~~~
                    write_line
exit status 1
'frame_link' does not name a type; did you mean 'write_line'?
`

**Comment by STONElibrary** [comment]
Sorry, I messed up several files when I updated the version. I have submitted the request of updating the library to the arduino official, but the library file found in IDE currently still contains the file of version 1.0.9. I am also very surprised, you can download the compressed package on this webpage, and it can be compiled through
